name: sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.0.5
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.3.0
  injectable_generator: ^1.5.4

flutter_gen:
  output: lib/generated/
  line_length: 120

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/colors/

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/test_image.png"
  image_path_android: "assets/images/test_image.png"
  adaptive_icon_background: "assets/images/test_image.png"
  adaptive_icon_foreground: "assets/images/test_image.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/test_image.png
  fullscreen: true
  android_12:
    image: "assets/images/test_image.png"